version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Jakarta
    target-branch: master
    open-pull-requests-limit: 99
    groups:
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint"
      typescript:
        patterns:
          - "@typescript-eslint/*"
          - "typescript"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Jakarta
    target-branch: master
    open-pull-requests-limit: 99
    groups:
      major:
        update-types:
          - major
        patterns:
          - '*'
      nonMajor:
        update-types:
          - minor
          - patch
        patterns:
          - '*'
