version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: master
  reviewers:
  - Hazmi35
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope