module.exports = {
    parserOptions: {
        ecmaVersion: 2020
    },
    extends: "eslint:recommended",
    env: {
        es6: true
    },
    rules: {
        "for-director": 0,
        "getter-return": 0,
        "no-async-promise-executor": 1,
        "no-await-in-loop": 0,
        "no-compare-neg-zero": 2,
        "no-cond-assign": 1,
        "no-console": 1,
        "no-constant-condition": 0,
        "no-control-regex": 0,
        "no-debugger": 2,
        "no-dupe-args": 2,
        "no-dupe-else-if": 2,
        "no-dupe-keys": 2,
        "no-duplicate-case": 2,
        "no-empty": 1,
        "no-empty-character-class": 1,
        "no-ex-assign": 0,
        "no-extra-boolean-cast": 0,
        "no-extra-parens": 0,
        "no-extra-semi": 2,
        "no-func-assign": 1,
        "no-import-assign": 1,
        "no-inner-declarations": 0,
        "no-invalid-regexp": 1,
        "no-irregular-whitespace": [2, {
			skipStrings: true,
			skipComments: true,
			skipRegExps: true,
			skipTemplates: true,
        }],
        "no-loss-of-precision": 1,
        "no-misleading-character-class": 1,
        "no-obj-calls": 1,
        "no-promise-executor-return": 0,
        "no-prototype-builtins": 0,
        "no-regex-spaces": 1,
        "no-setter-return": 1,
        "no-sparse-arrays": 1,
        "no-template-curly-in-string": 1,
        "no-unexpected-multiline": 2,
        "no-unreachable": 1,
        "no-unreachable-loop": 1,
        "no-unsafe-finally": 1,
        "no-unsafe-negation": 2,
        "use-isnan": 2,
        "valid-typeof": 2,
    }    
};