name: Lint code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    uses: Hazmi35/workflows/.github/workflows/pnpm-eslint.yaml@master
    secrets: inherit